### ISSUE TITLE
Cannot finish ./configure

### ISSUE THREAD

**Issue by hb0nes** [snhilde/statusbar3#1]
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'

I received zero other errors.

**Comment by hb0nes** [comment]
I ran this 
```
 aclocal
autoconf
autoheader
automake --add-missing
```
After that it worked.

**Comment by snhilde** [comment]
@hb0nes,
I really appreciate you opening this issue. It looks like I probably didn't test the build process with a clean pull like I should have.

I committed the rest of the autotools files as you referenced, and a clean pull is working for me on two different systems.

Any chance you could pull down a clean version and try the process (`./configure && make`) again to make sure it's looking good now?
